export interface Node {
  id: number;
  name: string;
  description: string[];
  imageSrc: string;
  position: { left?: number; top?: number; bottom?: number; right?: number };
  cost: number;
  isSelected: boolean;
  isRemovable?: boolean;
  dependsOn?: number;
  children: number[];
}

export const ALL_NODES: Node[] = [
  {
    id: 0,
    name: "Steam Technology",
    description: ["Basic technology."],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 20, top: 300 },
    cost: 0,
    isSelected: true,
    isRemovable: false,
    children: [1, 2, 3, 4, 5],
  },
  {
    id: 1,
    name: "Bearings and Pulleys",
    description: ["Fisherman Cottage: food generation +20%"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 320, top: 200 },
    cost: 100,
    children: [6],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: 2,
    name: "Assault Rifle",
    description: ["New unit: Soldier"],
    imageSrc: "/src/assets/image/soldier.png",
    position: { left: 320, top: 330 },
    cost: 120,
    children: [7, 8],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: 3,
    name: "Mercenaries I",
    description: ["Extra unit at start: Ranger"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 320, top: 480 },
    cost: 100,
    children: [9],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: 4,
    name: "High-Rise Defenses I",
    description: ["New structure: Wooden Tower"],
    imageSrc: "/src/assets/image/wooden-tower.png",
    position: { left: 320, top: 550 },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [10],
  },
  {
    id: 5,
    name: "Logistics",
    description: ["+40 Gold income", "+20 Resource Storage"],
    imageSrc: "/src/assets/image/logistics.png",
    position: { left: 320, bottom: 210 },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [11, 12],
  },
  {
    id: 6,
    name: "Efficient Turbines",
    description: ["Mill: Energy Supply +30%"],
    imageSrc: "/src/assets/image/thunder.png",
    position: { left: 620, top: 200 },
    cost: 120,
    dependsOn: 1,
    children: [],
    isSelected: false,
  },
  {
    id: 7,
    name: "Military Training",
    description: [
      "Buildings: Defensive Barriers +20%",
      "Extra unit at start: Soldier",
    ],
    imageSrc: "/src/assets/image/stone-door.png",
    position: { left: 620, top: 265 },
    cost: 100,
    children: [],
    dependsOn: 2,
    isSelected: false,
  },
  {
    id: 8,
    name: "Hunting Weapons",
    description: ["Hunterman Cottage: Food generation +20%"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 620, top: 330 },
    cost: 100,
    children: [],
    dependsOn: 2,
    isSelected: false,
  },
  {
    id: 9,
    name: "Mercenaries II",
    description: ["Extra unit at start: Sniper"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 620, top: 480 },
    cost: 100,
    children: [],
    dependsOn: 3,
    isSelected: false,
  },
  {
    id: 10,
    name: "Wood Buttresses",
    description: ["Wood Gate, Wood Wall, Wood Tower: +20% HP"],
    imageSrc: "/src/assets/image/castle.png",
    position: { left: 620, top: 550 },
    cost: 120,
    children: [],
    dependsOn: 4,
    isSelected: false,
  },
  {
    id: 11,
    name: "Basic Supplies",
    description: ["+20 Food Supply", "+20 Energy Supply"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 620, top: 620 },
    cost: 100,
    children: [],
    dependsOn: 5,
    isSelected: false,
  },
  {
    id: 12,
    name: "Gold Transportation",
    description: ["+200 Gold every train"],
    imageSrc: "/src/assets/image/train.png",
    position: { left: 620, bottom: 170 },
    cost: 100,
    children: [],
    dependsOn: 5,
    isSelected: false,
  },
  {
    id: 13,
    name: "Expert Workshops",
    description: ["New building: Cottage"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 950, top: 400 },
    cost: 240,
    children: [14],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: 14,
    name: "Cereal Farming",
    description: ["New building: Farm"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 1220, top: 200 },
    cost: 120,
    children: [],
    dependsOn: 13,
    isSelected: false,
  },
];
