import type { Node } from "../utils";
import {
  COLUMN_8_LEFT,
  LINE_10_HEIGHT,
  LINE_2_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_8_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_8_NODES: Node[] = [
  {
    id: NODE_IDS.TESLA_COILS,
    name: "Tesla Coils",
    description: [
      "Command Center: Energy transfer range +4",
      "Command Center: Energy supply +20%",
    ],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: COLUMN_8_LEFT, top: LINE_2_HEIGHT },
    cost: 100,
    children: [NODE_IDS.ADVANCED_TESLA_TRANSFER, NODE_IDS.PLASMA_SPHERES],
    dependsOn: NODE_IDS.ADVANCED_CONSTRUCTION,
    isSelected: false,
  },
  {
    id: NODE_IDS.THERMAL_ENERGY,
    name: "Thermal Energy",
    description: ["New building: Power Plant"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: COLUMN_8_LEFT, top: LINE_3_HEIGHT },
    cost: 120,
    children: [NODE_IDS.EXPLOSIVES],
    dependsOn: NODE_IDS.ADVANCED_CONSTRUCTION,
    isSelected: false,
  },
  {
    id: NODE_IDS.ADVANCED_TRAINING,
    name: "Advanced Training",
    description: ["Soldier, Ranger, Sniper: Training time -10%"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: COLUMN_8_LEFT, top: LINE_4_HEIGHT },
    cost: 100,
    children: [NODE_IDS.MILITARY_TACTICS],
    dependsOn: NODE_IDS.ADVANCED_CONSTRUCTION,
    isSelected: false,
  },
  {
    id: NODE_IDS.CONCRETE,
    name: "Concrete",
    description: ["New building: Stone Wall", "New building: Stone Gate"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: COLUMN_8_LEFT, top: LINE_6_HEIGHT },
    cost: 120,
    children: [NODE_IDS.CURRENCY, NODE_IDS.HIGH_RISE_DEFENSES_II],
    dependsOn: NODE_IDS.ADVANCED_CONSTRUCTION,
    isSelected: false,
  },
  {
    id: NODE_IDS.CHEMISTRY,
    name: "Chemistry",
    description: ["Soldier: Damage +20%"],
    imageSrc: "/src/assets/image/sniper-skull.png",
    position: { left: COLUMN_8_LEFT, top: LINE_8_HEIGHT },
    cost: 120,
    children: [NODE_IDS.INSULATING_MATERIALS, NODE_IDS.AUTONOMOUS_WEAPONS],
    dependsOn: NODE_IDS.ADVANCED_CONSTRUCTION,
    isSelected: false,
  },
  {
    id: NODE_IDS.IRON_TRANSPORTATION,
    name: "Iron Transportation",
    description: ["+6 Iron every Train"],
    imageSrc: "/src/assets/image/train.png",
    position: { left: COLUMN_8_LEFT, top: LINE_10_HEIGHT },
    cost: 120,
    children: [NODE_IDS.OIL_TRANSPORTATION],
    dependsOn: NODE_IDS.STONE_TRANSPORTATION,
    isSelected: false,
  },
];
