import type { Node } from "../utils";
import {
  COLUMN_13_LEFT,
  LINE_2_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_7_HEIGHT,
  LINE_8_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_13_NODES: Node[] = [
  {
    id: NODE_IDS.PNEUMATIC_JOINTS,
    name: "Pneumatic Joints",
    description: ["Oil platform: Oil production +1"],
    imageSrc: "/assets/image/oil.png",
    position: { left: COLUMN_13_LEFT, top: LINE_2_HEIGHT },
    cost: 120,
    children: [NODE_IDS.MECHANICAL_EXOSKELETONS, NODE_IDS.ARTICULATED_VEHICLES],
    dependsOn: NODE_IDS.MECHANICAL_ENGINEERING,
    isSelected: false,
  },
  {
    id: NODE_IDS.RADAR,
    name: "Radar",
    description: ["New building: Radar"],
    imageSrc: "/assets/image/radar.png",
    position: { left: COLUMN_13_LEFT, top: LINE_3_HEIGHT },
    cost: 140,
    children: [NODE_IDS.COMBAT_ARTILLERY],
    dependsOn: NODE_IDS.MECHANICAL_ENGINEERING,
    isSelected: false,
  },
  {
    id: NODE_IDS.ADVANCED_RESEARCH,
    name: "Advanced Research",
    description: ["-25% Research time"],
    imageSrc: "/assets/image/potion.png",
    position: { left: COLUMN_13_LEFT, top: LINE_4_HEIGHT },
    cost: 140,
    children: [],
    dependsOn: NODE_IDS.STEEL_TURBINES,
    isSelected: false,
  },
  {
    id: NODE_IDS.TUNGSTEN_SAW,
    name: "Tungsten Saw",
    description: ["Sawmill: Woodcutting +10%"],
    imageSrc: "/assets/image/communism.png",
    position: { left: COLUMN_13_LEFT, top: LINE_7_HEIGHT },
    cost: 120,
    children: [],
    dependsOn: NODE_IDS.TITANIUM,
    isSelected: false,
  },
  {
    id: NODE_IDS.TUNGSTEN_TOOLS,
    name: "Tungsten Tools",
    description: ["New building: Advanced Mill"],
    imageSrc: "/assets/image/tungsten-tools.png",
    position: { left: COLUMN_13_LEFT, top: LINE_8_HEIGHT },
    cost: 160,
    children: [],
    dependsOn: NODE_IDS.TITANIUM,
    isSelected: false,
  },
  {
    id: NODE_IDS.BARBED_WIRE,
    name: "Barbed Wire",
    description: ["New building: Wire fence trap"],
    imageSrc: "/assets/image/barbed-wire.png",
    position: { left: COLUMN_13_LEFT, top: LINE_9_HEIGHT },
    cost: 120,
    children: [NODE_IDS.CARBON_STEEL],
    dependsOn: NODE_IDS.TITANIUM,
    isSelected: false,
  },
];
