import type { Node } from "../utils";
import {
  COLUMN_4_LEFT,
  LINE_10_HEIGHT,
  LINE_2_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_7_HEIGHT,
  LINE_8_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_4_NODES: Node[] = [
  {
    id: NODE_IDS.CEREAL_FARMING,
    name: "Cereal Farming",
    description: ["New building: Farm"],
    imageSrc: "/assets/image/farm.png",
    position: { left: COLUMN_4_LEFT, top: LINE_2_HEIGHT },
    cost: 120,
    children: [NODE_IDS.COMMERCE],
    dependsOn: NODE_IDS.EXPERT_WORKSHOPS,
    isSelected: false,
  },
  {
    id: NODE_IDS.REINFORCED_ARMOR,
    name: "Reinforced Armor",
    description: ["Soldier: Armor +20%"],
    imageSrc: "/assets/image/shield.png",
    position: { left: COLUMN_4_LEFT, top: LINE_3_HEIGHT },
    cost: 100,
    children: [NODE_IDS.PROFESSIONAL_SOLDER],
    dependsOn: NODE_IDS.EXPERT_WORKSHOPS,
    isSelected: false,
  },
  {
    id: NODE_IDS.REINFORCED_PROJECTILES,
    name: "Reinforced Projectiles",
    description: ["Ranger: Damage +20%"],
    imageSrc: "/assets/image/sniper-skull.png",
    position: { left: COLUMN_4_LEFT, top: LINE_4_HEIGHT },
    cost: 100,
    children: [NODE_IDS.MECHANIZED_WEAPONS],
    dependsOn: NODE_IDS.EXPERT_WORKSHOPS,
    isSelected: false,
  },
  {
    id: NODE_IDS.OPTICS,
    name: "Optics",
    description: ["Command Center: View Range +5"],
    imageSrc: "/assets/image/eye.png",
    position: { left: COLUMN_4_LEFT, top: LINE_6_HEIGHT },
    cost: 100,
    children: [NODE_IDS.ADVANCED_LENSES, NODE_IDS.LONG_RANGE_RIFLE],
    dependsOn: NODE_IDS.EXPERT_WORKSHOPS,
    isSelected: false,
  },
  {
    id: NODE_IDS.BARRICADES,
    name: "Barricades",
    description: ["New Building: Stakes Trap"],
    imageSrc: "/assets/image/barricades.png",
    position: { left: COLUMN_4_LEFT, top: LINE_7_HEIGHT },
    cost: 80,
    children: [],
    dependsOn: NODE_IDS.WOOD_BUTTRESSES,
    isSelected: false,
  },
  {
    id: NODE_IDS.MEDICINE,
    name: "Medicine",
    description: ["Soldier, Ranger, Sniper: +20% Life"],
    imageSrc: "/assets/image/health.png",
    position: { left: COLUMN_4_LEFT, top: LINE_8_HEIGHT },
    cost: 140,
    children: [NODE_IDS.ADVANCED_LABORATORY],
    dependsOn: NODE_IDS.BASIC_SUPLIES,
    isSelected: false,
  },
  {
    id: NODE_IDS.STRUCTURE_RECYCLING,
    name: "Structure Recycling",
    description: ["+30% of cost returned on Destroying"],
    imageSrc: "/assets/image/wooden-gold.png",
    position: { left: COLUMN_4_LEFT, top: LINE_9_HEIGHT },
    cost: 140,
    children: [NODE_IDS.CORPSE_RECYCLING],
    dependsOn: NODE_IDS.MECHANIZED_STORAGE,
    isSelected: false,
  },
  {
    id: NODE_IDS.WOOD_TRANSPORTATION,
    name: "Wood Transportation",
    description: ["+15 Wood every Train"],
    imageSrc: "/assets/image/train.png",
    position: { left: COLUMN_4_LEFT, top: LINE_10_HEIGHT },
    cost: 140,
    children: [NODE_IDS.STONE_TRANSPORTATION],
    dependsOn: NODE_IDS.GOLD_TRANSPORTATION,
    isSelected: false,
  },
];
