import { NODE_IDS, type Node } from "./all-nodes";

export const COLUMN_1_NODES: Node[] = [
  {
    id: NODE_IDS.STEAM_TECHNOLOGY,
    name: "Steam Technology",
    description: ["Basic technology."],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 20, top: 300 },
    cost: 0,
    isSelected: true,
    isRemovable: false,
    children: [
      NODE_IDS.BEARINGS_AND_PULLEYS,
      NODE_IDS.ASSAULT_RIFLE,
      NODE_IDS.MERCENARIES_I,
      NODE_IDS.HIGH_RISE_DEFENSES_I,
      NODE_IDS.LOGISTICS,
    ],
  },
  {
    id: NODE_IDS.BEARINGS_AND_PULLEYS,
    name: "Bearings and Pulleys",
    description: ["Fisherman Cottage: food generation +20%"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 350, top: 150 },
    cost: 100,
    children: [NODE_IDS.EFFICIENT_TURBINES],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.ASSAULT_RIFLE,
    name: "Assault Rifle",
    description: ["New unit: Soldier"],
    imageSrc: "/src/assets/image/soldier.png",
    position: { left: 350, top: 260 },
    cost: 120,
    children: [NODE_IDS.MILITARY_TRAINING, NODE_IDS.HUNTING_WEAPONS],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.MERCENARIES_I,
    name: "Mercenaries I",
    description: ["Extra unit at start: Ranger"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 350, top: 350 },
    cost: 100,
    children: [NODE_IDS.MERCENARIES_II],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.HIGH_RISE_DEFENSES_I,
    name: "High-Rise Defenses I",
    description: ["New structure: Wooden Tower"],
    imageSrc: "/src/assets/image/wooden-tower.png",
    position: { left: 350, top: 410 },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [NODE_IDS.WOOD_BUTTRESSES],
  },
  {
    id: NODE_IDS.LOGISTICS,
    name: "Logistics",
    description: ["+40 Gold income", "+20 Resource Storage"],
    imageSrc: "/src/assets/image/logistics.png",
    position: { left: 350, bottom: 140 },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [
      NODE_IDS.BASIC_SUPLIES,
      NODE_IDS.GOLD_TRANSPORTATION,
      NODE_IDS.MECHANIZED_STORAGE,
    ],
  },
];
