import { NODE_IDS, type Node } from "./all-nodes";

export const COLUMN_2_NODES: Node[] = [
  {
    id: NODE_IDS.EFFICIENT_TURBINES,
    name: "Efficient Turbines",
    description: ["Mill: Energy Supply +30%"],
    imageSrc: "/src/assets/image/thunder.png",
    position: { left: 640, top: 150 },
    cost: 120,
    dependsOn: NODE_IDS.BEARINGS_AND_PULLEYS,
    children: [],
    isSelected: false,
  },
  {
    id: NODE_IDS.MILITARY_TRAINING,
    name: "Military Training",
    description: [
      "Buildings: Defensive Barriers +20%",
      "Extra unit at start: Soldier",
    ],
    imageSrc: "/src/assets/image/stone-door.png",
    position: { left: 640, top: 205 },
    cost: 100,
    children: [],
    dependsOn: NODE_IDS.ASSAULT_RIFLE,
    isSelected: false,
  },
  {
    id: NODE_IDS.HUNTING_WEAPONS,
    name: "Hunting Weapons",
    description: ["Hunterman Cottage: Food generation +20%"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 640, top: 260 },
    cost: 100,
    children: [],
    dependsOn: NODE_IDS.ASSAULT_RIFLE,
    isSelected: false,
  },
  {
    id: NODE_IDS.MERCENARIES_II,
    name: "Mercenaries II",
    description: ["Extra unit at start: Sniper"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: 640, top: 350 },
    cost: 100,
    children: [],
    dependsOn: NODE_IDS.MERCENARIES_I,
    isSelected: false,
  },
  {
    id: NODE_IDS.WOOD_BUTTRESSES,
    name: "Wood Buttresses",
    description: ["Wood Gate, Wood Wall, Wood Tower: +20% HP"],
    imageSrc: "/src/assets/image/castle.png",
    position: { left: 640, top: 410 },
    cost: 120,
    children: [],
    dependsOn: NODE_IDS.HIGH_RISE_DEFENSES_I,
    isSelected: false,
  },
  {
    id: NODE_IDS.BASIC_SUPLIES,
    name: "Basic Supplies",
    description: ["+20 Food Supply", "+20 Energy Supply"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: 640, top: 470 },
    cost: 100,
    children: [],
    dependsOn: NODE_IDS.LOGISTICS,
    isSelected: false,
  },
  {
    id: NODE_IDS.GOLD_TRANSPORTATION,
    name: "Gold Transportation",
    description: ["+200 Gold every train"],
    imageSrc: "/src/assets/image/train.png",
    position: { left: 640, bottom: 90 },
    cost: 100,
    children: [],
    dependsOn: NODE_IDS.LOGISTICS,
    isSelected: false,
  },
];
