import type { Node } from "../utils";
import {
  COLUMN_12_LEFT,
  LINE_10_HEIGHT,
  LINE_1_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_8_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_12_NODES: Node[] = [
  {
    id: NODE_IDS.RAY_CONDENSER,
    name: "Ray Condenser",
    description: ["New wonder: The Lightning Spire"],
    imageSrc: "/assets/image/ray-condenser.png",
    position: { left: COLUMN_12_LEFT, top: LINE_1_HEIGHT },
    cost: 200,
    children: [],
    dependsOn: NODE_IDS.ADVANCED_TESLA_TRANSFER,
    isSelected: false,
  },
  {
    id: NODE_IDS.MECHANICAL_ENGINEERING,
    name: "Mechanical Engineering",
    description: ["New building: Engineering Center", "New unit: Lucifer"],
    imageSrc: "/assets/image/mechanical-engineering.png",
    position: { left: COLUMN_12_LEFT, top: LINE_3_HEIGHT },
    cost: 160,
    children: [NODE_IDS.RADAR, NODE_IDS.PNEUMATIC_JOINTS],
    dependsOn: NODE_IDS.ADVANCED_MACHINERY,
    isSelected: false,
  },
  {
    id: NODE_IDS.STEEL_TURBINES,
    name: "Steel Turbines",
    description: ["New building: Advanced Mill"],
    imageSrc: "/assets/image/steel-turbines.png",
    position: { left: COLUMN_12_LEFT, top: LINE_4_HEIGHT },
    cost: 140,
    children: [NODE_IDS.ADVANCED_RESEARCH],
    dependsOn: NODE_IDS.ADVANCED_MACHINERY,
    isSelected: false,
  },
  {
    id: NODE_IDS.BIOCHEMISTRY,
    name: "Biochemistry",
    description: ["New building: Advanced Farm"],
    imageSrc: "/assets/image/biochemistry.png",
    position: { left: COLUMN_12_LEFT, top: LINE_6_HEIGHT },
    cost: 160,
    children: [NODE_IDS.CHEMICAL_TRANSMUTATION],
    dependsOn: NODE_IDS.ADVANCED_MACHINERY,
    isSelected: false,
  },
  {
    id: NODE_IDS.TITANIUM,
    name: "Titanium",
    description: ["Buildings: Defensive Barriers +10%"],
    imageSrc: "/assets/image/stone-door.png",
    position: { left: COLUMN_12_LEFT, top: LINE_8_HEIGHT },
    cost: 120,
    children: [
      NODE_IDS.TUNGSTEN_TOOLS,
      NODE_IDS.TUNGSTEN_SAW,
      NODE_IDS.BARBED_WIRE,
    ],
    dependsOn: NODE_IDS.ADVANCED_MACHINERY,
    isSelected: false,
  },
  {
    id: NODE_IDS.OIL_TRANSPORTATION,
    name: "Oil Transportation",
    description: ["+5 Oil every train"],
    imageSrc: "/assets/image/train.png",
    position: { left: COLUMN_12_LEFT, top: LINE_10_HEIGHT },
    cost: 240,
    children: [NODE_IDS.INGOT_TRANSPORT],
    dependsOn: NODE_IDS.IRON_TRANSPORTATION,
    isSelected: false,
  },
];
