import type { Node } from "../utils";
import {
  COLUMN_1_LEFT,
  INITIAL_LEFT,
  LINE_2_HEIGHT,
  LINE_4_HEIGHT,
  LINE_5_HEIGHT,
  LINE_6_HEIGHT,
  LINE_7_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_1_NODES: Node[] = [
  {
    id: NODE_IDS.STEAM_TECHNOLOGY,
    name: "Steam Technology",
    description: ["Basic technology."],
    imageSrc: "/assets/image/potion.png",
    position: { left: INITIAL_LEFT, top: LINE_5_HEIGHT },
    cost: 0,
    isSelected: true,
    isRemovable: false,
    children: [
      NODE_IDS.BEARINGS_AND_PULLEYS,
      NODE_IDS.ASSAULT_RIFLE,
      NODE_IDS.MERCENARIES_I,
      NODE_IDS.HIGH_RISE_DEFENSES_I,
      NODE_IDS.LOGISTICS,
      NODE_IDS.EXPERT_WORKSHOPS,
    ],
  },
  {
    id: NODE_IDS.BEARINGS_AND_PULLEYS,
    name: "Bearings and Pulleys",
    description: ["Fisherman Cottage: food generation +20%"],
    imageSrc: "/assets/image/corn.png",
    position: { left: COLUMN_1_LEFT, top: LINE_2_HEIGHT },
    cost: 100,
    children: [NODE_IDS.EFFICIENT_TURBINES],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.ASSAULT_RIFLE,
    name: "Assault Rifle",
    description: ["New unit: Soldier"],
    imageSrc: "/assets/image/soldier.png",
    position: { left: COLUMN_1_LEFT, top: LINE_4_HEIGHT },
    cost: 120,
    children: [NODE_IDS.MILITARY_TRAINING, NODE_IDS.HUNTING_WEAPONS],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.MERCENARIES_I,
    name: "Mercenaries I",
    description: ["Extra unit at start: Ranger"],
    imageSrc: "/assets/image/potion.png",
    position: { left: COLUMN_1_LEFT, top: LINE_6_HEIGHT },
    cost: 100,
    children: [NODE_IDS.MERCENARIES_II],
    dependsOn: 0,
    isSelected: false,
  },
  {
    id: NODE_IDS.HIGH_RISE_DEFENSES_I,
    name: "High-Rise Defenses I",
    description: ["New structure: Wooden Tower"],
    imageSrc: "/assets/image/wooden-tower.png",
    position: { left: COLUMN_1_LEFT, top: LINE_7_HEIGHT },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [NODE_IDS.WOOD_BUTTRESSES],
  },
  {
    id: NODE_IDS.LOGISTICS,
    name: "Logistics",
    description: ["+40 Gold income", "+20 Resource Storage"],
    imageSrc: "/assets/image/logistics.png",
    position: { left: COLUMN_1_LEFT, top: LINE_9_HEIGHT },
    cost: 100,
    isSelected: false,
    dependsOn: 0,
    children: [
      NODE_IDS.BASIC_SUPLIES,
      NODE_IDS.GOLD_TRANSPORTATION,
      NODE_IDS.MECHANIZED_STORAGE,
    ],
  },
];
