import type { Node } from "../utils";
import {
  COLUMN_17_LEFT,
  LINE_10_HEIGHT,
  LINE_1_HEIGHT,
  LINE_2_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_7_HEIGHT,
  LINE_8_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_17_NODES: Node[] = [
  {
    id: NODE_IDS.LASER,
    name: "Laser",
    description: ["Titan: +25% damage"],
    imageSrc: "/src/assets/image/sniper-skull.png",
    position: { left: COLUMN_17_LEFT, top: LINE_1_HEIGHT },
    cost: 200,
    children: [],
    dependsOn: NODE_IDS.ADVANCED_AMMUNITION,
    isSelected: false,
  },
  {
    id: NODE_IDS.GENETIC_ENGINEERING,
    name: "Genetic Engineering",
    description: ["New unit: Mutant"],
    imageSrc: "/src/assets/image/genetic-engineering.png",
    position: { left: COLUMN_17_LEFT, top: LINE_2_HEIGHT },
    cost: 300,
    children: [],
    dependsOn: NODE_IDS.NANOMATERIALS,
    isSelected: false,
  },
  {
    id: NODE_IDS.AUGMENTED_REALITY,
    name: "Augmented Reality",
    description: ["Sniper: View range, Attack range +1", "Sniper: +20% damage"],
    imageSrc: "/src/assets/image/eye.png",
    position: { left: COLUMN_17_LEFT, top: LINE_3_HEIGHT },
    cost: 220,
    children: [],
    dependsOn: NODE_IDS.NANOMATERIALS,
    isSelected: false,
  },
  {
    id: NODE_IDS.DIAMOND_TOOLS,
    name: "Diamond Tools",
    description: ["Advanced Quarry: Mining resources +20%"],
    imageSrc: "/src/assets/image/corn.png",
    position: { left: COLUMN_17_LEFT, top: LINE_4_HEIGHT },
    cost: 240,
    children: [],
    dependsOn: NODE_IDS.NANOMATERIALS,
    isSelected: false,
  },
  {
    id: NODE_IDS.HIGH_ENERGY_PLASMA,
    name: "High Energy Plasma",
    description: [
      "Shocking Tower: Attack range +1",
      "Shocking Tower: View range +1",
    ],
    imageSrc: "/src/assets/image/circle-plus.png",
    position: { left: COLUMN_17_LEFT, top: LINE_6_HEIGHT },
    cost: 220,
    children: [],
    dependsOn: NODE_IDS.SUPERCONDUCTOR,
    isSelected: false,
  },
  {
    id: NODE_IDS.OPTIMAL_TESLA_TRANSFER,
    name: "Optima Tesla Transfer",
    description: [
      "Tesla Tower: Energy transfer radius +1",
      "Tesla Tower: View range +1",
    ],
    imageSrc: "/src/assets/image/energy-tower.png",
    position: { left: COLUMN_17_LEFT, top: LINE_7_HEIGHT },
    cost: 240,
    children: [],
    dependsOn: NODE_IDS.SUPERCONDUCTOR,
    isSelected: false,
  },
  {
    id: NODE_IDS.SOLAR_ENERGY,
    name: "Solar Energy",
    description: ["Buildings: -20% energy needed"],
    imageSrc: "/src/assets/image/thunder.png",
    position: { left: COLUMN_17_LEFT, top: LINE_8_HEIGHT },
    cost: 240,
    children: [],
    dependsOn: NODE_IDS.SUPERCONDUCTOR,
    isSelected: false,
  },
  {
    id: NODE_IDS.DEEP_DRILLING,
    name: "Deep Drilling",
    description: ["Oil Platform: +20% Oil production"],
    imageSrc: "/src/assets/image/oil.png",
    position: { left: COLUMN_17_LEFT, top: LINE_9_HEIGHT },
    cost: 240,
    children: [],
    dependsOn: NODE_IDS.SUPERCONDUCTOR,
    isSelected: false,
  },
  {
    id: NODE_IDS.ARTILLERY_TRANSPORT,
    name: "Artillery Transport",
    description: ["+1 Wasp with every train"],
    imageSrc: "/src/assets/image/potion.png",
    position: { left: COLUMN_17_LEFT, top: LINE_10_HEIGHT },
    cost: 400,
    children: [],
    dependsOn: NODE_IDS.INGOT_TRANSPORT,
    isSelected: false,
  },
];
