import type { Node } from "../utils";
import {
  COLUMN_5_LEFT,
  LINE_2_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_7_HEIGHT,
  LINE_8_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";
import { NODE_IDS } from "./node-ids";

export const COLUMN_5_NODES: Node[] = [
  {
    id: NODE_IDS.COMMERCE,
    name: "Commerce",
    description: ["New building: Market"],
    imageSrc: "/assets/image/commerce.png",
    position: { left: COLUMN_5_LEFT, top: LINE_2_HEIGHT },
    cost: 120,
    children: [NODE_IDS.LODGING],
    dependsOn: NODE_IDS.CEREAL_FARMING,
    isSelected: false,
  },
  {
    id: NODE_IDS.PROFESSIONAL_SOLDER,
    name: "Professional Soldier",
    description: ["Extra unit at start: Soldier"],
    imageSrc: "/assets/image/potion.png",
    position: { left: COLUMN_5_LEFT, top: LINE_3_HEIGHT },
    cost: 80,
    children: [],
    dependsOn: NODE_IDS.REINFORCED_ARMOR,
    isSelected: false,
  },
  {
    id: NODE_IDS.MECHANIZED_WEAPONS,
    name: "Mechanized Weapons",
    description: ["New building: Ballista"],
    imageSrc: "/assets/image/mechanized-weapons.png",
    position: { left: COLUMN_5_LEFT, top: LINE_4_HEIGHT },
    cost: 140,
    children: [NODE_IDS.PREFABRICATED_PARTS],
    dependsOn: NODE_IDS.REINFORCED_PROJECTILES,
    isSelected: false,
  },
  {
    id: NODE_IDS.ADVANCED_LENSES,
    name: "Advanced Lenses",
    description: ["New building: Lookout Tower"],
    imageSrc: "/assets/image/advanced-lenses.png",
    position: { left: COLUMN_5_LEFT, top: LINE_6_HEIGHT },
    cost: 120,
    children: [NODE_IDS.TELESCOPIC_SIGHT],
    dependsOn: NODE_IDS.OPTICS,
    isSelected: false,
  },
  {
    id: NODE_IDS.LONG_RANGE_RIFLE,
    name: "Long Range Rifle",
    description: ["Soldier: View Range +1", "Soldier: Attack Range +1"],
    imageSrc: "/assets/image/eye.png",
    position: { left: COLUMN_5_LEFT, top: LINE_7_HEIGHT },
    cost: 100,
    children: [NODE_IDS.GLOBAL_VISION],
    dependsOn: NODE_IDS.OPTICS,
    isSelected: false,
  },
  {
    id: NODE_IDS.ADVANCED_LABORATORY,
    name: "Advanced Laboratory",
    description: ["-25% Research time"],
    imageSrc: "/assets/image/potion.png",
    position: { left: COLUMN_5_LEFT, top: LINE_8_HEIGHT },
    cost: 120,
    children: [],
    dependsOn: NODE_IDS.MEDICINE,
    isSelected: false,
  },
  {
    id: NODE_IDS.CORPSE_RECYCLING,
    name: "Corpse Recycling",
    description: ["+1 Gold per infected killed"],
    imageSrc: "/assets/image/gold.png",
    position: { left: COLUMN_5_LEFT, top: LINE_9_HEIGHT },
    cost: 120,
    children: [],
    dependsOn: NODE_IDS.STRUCTURE_RECYCLING,
    isSelected: false,
  },
];
