import type { Node } from "../../utils";
import { NODE_IDS } from "../node-ids";
import {
  COLUMN_9_LEFT,
  LINE_1_HEIGHT,
  LINE_3_HEIGHT,
  LINE_4_HEIGHT,
  LINE_6_HEIGHT,
  LINE_7_HEIGHT,
  LINE_8_HEIGHT,
  LINE_9_HEIGHT,
} from "./line-columns-values";

export const COLUMN_9_NODES: Node[] = [
  {
    id: NODE_IDS.ADVANCED_TESLA_TRANSFER,
    name: "Advanced Tesla Transfer",
    description: [
      "Tesla Tower: Energy transfer radius +1",
      "Tesla Tower: View range +1",
    ],
    imageSrc: "/assets/image/energy-tower.png",
    position: { left: COLUMN_9_LEFT, top: LINE_1_HEIGHT },
    cost: 200,
    children: [NODE_IDS.RAY_CONDENSER],
    dependsOn: NODE_IDS.TESLA_COILS,
    isSelected: false,
  },
  {
    id: NODE_IDS.EXPLOSIVES,
    name: "Explosives",
    description: ["New building: Land Mine"],
    imageSrc: "/assets/image/explosives.png",
    position: { left: COLUMN_9_LEFT, top: LINE_3_HEIGHT },
    cost: 120,
    children: [],
    dependsOn: NODE_IDS.THERMAL_ENERGY,
    isSelected: false,
  },
  {
    id: NODE_IDS.MILITARY_TACTICS,
    name: "Military Tactics",
    description: ["Experience until Veteran: -20%"],
    imageSrc: "/assets/image/veteran.png",
    position: { left: COLUMN_9_LEFT, top: LINE_4_HEIGHT },
    cost: 120,
    children: [NODE_IDS.MILITARY_MASTERY],
    dependsOn: NODE_IDS.ADVANCED_TRAINING,
    isSelected: false,
  },
  {
    id: NODE_IDS.CURRENCY,
    name: "Currency",
    description: ["New building: Bank"],
    imageSrc: "/assets/image/currency.png",
    position: { left: COLUMN_9_LEFT, top: LINE_6_HEIGHT },
    cost: 140,
    children: [NODE_IDS.BLACK_MARKET],
    dependsOn: NODE_IDS.CONCRETE,
    isSelected: false,
  },
  {
    id: NODE_IDS.HIGH_RISE_DEFENSES_II,
    name: "High Rise Defenses II",
    description: ["New building: Stone Tower"],
    imageSrc: "/assets/image/high-rise-defenses-ii.png",
    position: { left: COLUMN_9_LEFT, top: LINE_7_HEIGHT },
    cost: 80,
    children: [NODE_IDS.REINFORCED_CONCRETE],
    dependsOn: NODE_IDS.CONCRETE,
    isSelected: false,
  },
  {
    id: NODE_IDS.INSULATING_MATERIALS,
    name: "Insulating Materials",
    description: ["Cottage: Energy needed -1", "Stone House: Energy needed -2"],
    imageSrc: "/assets/image/thunder.png",
    position: { left: COLUMN_9_LEFT, top: LINE_8_HEIGHT },
    cost: 140,
    children: [NODE_IDS.CLIMATE_CONTROL],
    dependsOn: NODE_IDS.CHEMISTRY,
    isSelected: false,
  },
  {
    id: NODE_IDS.AUTONOMOUS_WEAPONS,
    name: "Autonomous Weapons",
    description: ["New building: Wasp"],
    imageSrc: "/assets/image/autonomous-weapons.png",
    position: { left: COLUMN_9_LEFT, top: LINE_9_HEIGHT },
    cost: 120,
    children: [NODE_IDS.ARMORED_ATTACK_STATION],
    dependsOn: NODE_IDS.CHEMISTRY,
    isSelected: false,
  },
];
